/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Initiate Google OAuth login */
        get: operations["AuthController_googleAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Initiate GitHub OAuth login */
        get: operations["AuthController_githubAuth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/anonymous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create anonymous user session
         * @description Creates a temporary anonymous user with limited access (3 chat sessions, 5 files max)
         */
        post: operations["AuthController_createAnonymousSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a sign-in link
         * @description Emails a single-use link. Always returns 202, whether or not the address has an account, so the endpoint cannot be used to discover who is registered.
         */
        post: operations["AuthController_requestMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a sign-in link for a token
         * @description Consumes the token from the emailed link and returns a JWT. Tokens are single use.
         */
        post: operations["AuthController_verifyMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/migrate-anonymous": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move an anonymous session onto the signed-in account
         * @description Call after signing in, with the anonymous token held beforehand. Its chat sessions and files transfer to the authenticated account and the anonymous user is removed.
         */
        post: operations["AuthController_migrateAnonymous"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Returns user profile with usage statistics and account limits
         */
        get: operations["UsersController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List selectable models
         * @description Models the sidebar can offer, with their capabilities and whether a key is configured. Drives the model switcher.
         */
        get: operations["AiRouterController_listModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/prompt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process AI prompt
         * @description Sends a prompt to the selected model and returns the full response. Both sides of the exchange are saved to the chat session.
         */
        post: operations["AiRouterController_processPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/prompt/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stream an AI response
         * @description Server-sent events. Emits a `session` event, then a `delta` event per token chunk, then `done`. Errors arrive as an `error` event because headers are already sent.
         */
        post: operations["AiRouterController_streamPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user files
         * @description Returns all files owned by the authenticated user, organized by folder
         */
        get: operations["FilesController_getUserFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a file
         * @description Streams the file body as an attachment, reading from S3 when the file was offloaded.
         */
        get: operations["FilesController_downloadFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete file
         * @description Delete a specific file owned by the authenticated user
         */
        delete: operations["FilesController_deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_getUserChatSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_getChatSession"];
        put?: never;
        post?: never;
        delete: operations["ChatController_deleteChatSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_searchChatHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/byok": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List connected keys
         * @description Returns which providers have a key connected, with the last four characters as a hint. The key itself is never returned.
         */
        get: operations["ByokController_list"];
        put?: never;
        /**
         * Connect or replace a key
         * @description Validates the key against the provider, then stores it encrypted. Replaces any existing key for that provider.
         */
        post: operations["ByokController_upsert"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/byok/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect a key */
        delete: operations["ByokController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health
         * @description Reports process uptime and database connectivity. Returns 503 when a dependency is unreachable so uptime monitors and deploy gates can act on it.
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequestMagicLinkDto: {
            /**
             * @description Address to send the sign-in link to
             * @example nina@example.com
             */
            email: string;
        };
        ConsumeMagicLinkDto: {
            /**
             * @description The token from the emailed link
             * @example D8x1s7...
             */
            token: string;
        };
        MigrateAnonymousDto: {
            /**
             * @description The anonymous session token held before signing in. Its chat sessions and files move to the signed-in account.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            anonymous_token: string;
        };
        PromptRequestDto: {
            /**
             * @description User ID (automatically set from authenticated user)
             * @example cmi8tb6tv0000rdimxbtp39do
             */
            user_id?: string;
            /**
             * @description Model id to route to. Call GET /ai/models for the current list.
             * @example claude-opus-5
             */
            model: string;
            /**
             * @description Type of input being processed
             * @example text
             * @enum {string}
             */
            input_type: "text" | "code" | "image";
            /**
             * @description Additional context for the AI model
             * @example You are a helpful coding assistant
             */
            context?: string;
            /**
             * @description The prompt or question to send to the AI model
             * @example Write a function to calculate fibonacci numbers
             */
            prompt: string;
            /**
             * @description Source URL of an image selected on the page. Required when input_type is "image".
             * @example https://example.com/diagram.png
             */
            image_url?: string;
            /**
             * @description Continue an existing conversation. A new session is created when omitted.
             * @example cmi8tb6tv0000rdimxbtp39do
             */
            session_id?: string;
        };
        AiResponseDto: {
            /**
             * @description The AI-generated response
             * @example Here is a function to calculate fibonacci numbers:
             *
             *     function fibonacci(n) {
             *       if (n <= 1) return n;
             *       return fibonacci(n - 1) + fibonacci(n - 2);
             *     }
             */
            response: string;
            /**
             * @description The AI model that generated the response
             * @example gpt-4
             */
            model_used: string;
            /**
             * @description Timestamp when the response was generated
             * @example 2023-11-28T10:30:00.000Z
             */
            timestamp: string;
            /**
             * @description File type for automatic organization
             * @example js
             */
            file_type: string;
            /**
             * @description Folder for automatic organization
             * @example /code
             * @enum {string}
             */
            folder: "/code" | "/documents";
        };
        UpsertByokKeyDto: {
            /**
             * @description Which provider the key belongs to
             * @example anthropic
             * @enum {string}
             */
            provider: "anthropic" | "openai";
            /**
             * @description The API key. Encrypted before storage and never returned by any endpoint.
             * @example sk-ant-api03-...
             */
            api_key: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_googleAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to Google OAuth */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_githubAuth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirects to GitHub OAuth */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_createAnonymousSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anonymous user created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                        access_token?: string;
                        user?: {
                            /** @example cmi8tb6tv0000rdimxbtp39do */
                            id?: string;
                        };
                    };
                };
            };
        };
    };
    AuthController_requestMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestMagicLinkDto"];
            };
        };
        responses: {
            /** @description Link sent if the address is valid */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_verifyMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsumeMagicLinkDto"];
            };
        };
        responses: {
            /** @description Signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Link is invalid, expired or used */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_migrateAnonymous: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrateAnonymousDto"];
            };
        };
        responses: {
            /** @description Migration completed */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example 3 */
                        migratedSessions?: number;
                        /** @example 2 */
                        migratedFiles?: number;
                    };
                };
            };
            /** @description Invalid or unusable token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token does not belong to an anonymous account */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UsersController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example cmi8tb6tv0000rdimxbtp39do */
                        id?: string;
                        /** @example user@example.com */
                        email?: string | null;
                        /** @example google */
                        authProvider?: string | null;
                        /** @example free */
                        subscriptionTier?: string;
                        /** @example false */
                        isAnonymous?: boolean;
                        /** @example 5 */
                        chatSessionCount?: number;
                        /** @example 12 */
                        fileCount?: number;
                        limits?: {
                            /**
                             * @description -1 means unlimited
                             * @example -1
                             */
                            maxChatSessions?: number;
                            /**
                             * @description -1 means unlimited
                             * @example -1
                             */
                            maxFiles?: number;
                        };
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiRouterController_listModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiRouterController_processPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiResponseDto"];
                };
            };
            /** @description Unknown model or invalid input */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No API key configured for the selected provider */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiRouterController_streamPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptRequestDto"];
            };
        };
        responses: {
            /** @description Event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_getUserFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Files retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example file123 */
                        id?: string;
                        /** @example fibonacci.js */
                        filename?: string;
                        /** @example /code */
                        folder?: string;
                        /** @example js */
                        fileType?: string;
                        /** @example 2023-11-28T10:30:00.000Z */
                        createdAt?: string;
                    }[];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_downloadFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File ID to download */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FilesController_deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description File ID to delete */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description File not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_getUserChatSessions: {
        parameters: {
            query: {
                limit: string;
                cursor: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_getChatSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_deleteChatSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_searchChatHistory: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ByokController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Connected providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anonymous users cannot use BYOK */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ByokController_upsert: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertByokKeyDto"];
            };
        };
        responses: {
            /** @description Key stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The provider rejected the key */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Anonymous users cannot use BYOK */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server encryption key is not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ByokController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: "anthropic" | "openai";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No key connected for that provider */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description A dependency is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
